### ISSUE TITLE
Posts are randomly failing on Slack's side

### ISSUE THREAD

**Issue by itsthejoker** [KenzieAcademy/qbert#7]
```sh
Mar 12 14:38:30 ip-172-31-39-222 gunicorn[29651]: Exception in thread Thread-5:
Mar 12 14:38:30 ip-172-31-39-222 gunicorn[29651]: Traceback (most recent call last):
Mar 12 14:38:30 ip-172-31-39-222 gunicorn[29651]:   File "/home/ubuntu/.pyenv/versions/3.8.1/lib/python3.8/threading.py", line 932, in _bootstrap_inner
Mar 12 14:38:30 ip-172-31-39-222 gunicorn[29651]:     self.run()
Mar 12 14:38:30 ip-172-31-39-222 gunicorn[29651]:   File "/home/ubuntu/.pyenv/versions/3.8.1/lib/python3.8/threading.py", line 870, in run
Mar 12 14:38:30 ip-172-31-39-222 gunicorn[29651]:     self._target(*self._args, **self._kwargs)
Mar 12 14:38:30 ip-172-31-39-222 gunicorn[29651]:   File "/home/ubuntu/app/quackers/core.py", line 172, in process_question_followup
Mar 12 14:38:30 ip-172-31-39-222 gunicorn[29651]:     post_message_to_user(
Mar 12 14:38:30 ip-172-31-39-222 gunicorn[29651]:   File "/home/ubuntu/app/quackers/core.py", line 120, in post_message_to_user
Mar 12 14:38:30 ip-172-31-39-222 gunicorn[29651]:     client.chat_postEphemeral(
Mar 12 14:38:30 ip-172-31-39-222 gunicorn[29651]:   File "/home/ubuntu/app/.venv/lib/python3.8/site-packages/slack/web/client.py", line 543, in chat_postEphemeral
Mar 12 14:38:30 ip-172-31-39-222 gunicorn[29651]:     return self.api_call("chat.postEphemeral", json=kwargs)
Mar 12 14:38:30 ip-172-31-39-222 gunicorn[29651]:   File "/home/ubuntu/app/.venv/lib/python3.8/site-packages/slack/web/base_client.py", line 171, in api_call
Mar 12 14:38:30 ip-172-31-39-222 gunicorn[29651]:     return self._event_loop.run_until_complete(future)
Mar 12 14:38:30 ip-172-31-39-222 gunicorn[29651]:   File "/home/ubuntu/.pyenv/versions/3.8.1/lib/python3.8/asyncio/base_events.py", line 612, in run_until_complete
Mar 12 14:38:30 ip-172-31-39-222 gunicorn[29651]:     return future.result()
Mar 12 14:38:30 ip-172-31-39-222 gunicorn[29651]:   File "/home/ubuntu/app/.venv/lib/python3.8/site-packages/slack/web/base_client.py", line 226, in _send
Mar 12 14:38:30 ip-172-31-39-222 gunicorn[29651]:     return SlackResponse(**{**data, **res}).validate()
Mar 12 14:38:30 ip-172-31-39-222 gunicorn[29651]:   File "/home/ubuntu/app/.venv/lib/python3.8/site-packages/slack/web/slack_response.py", line 176, in validate
Mar 12 14:38:30 ip-172-31-39-222 gunicorn[29651]:     raise e.SlackApiError(message=msg, response=self)
Mar 12 14:38:30 ip-172-31-39-222 gunicorn[29651]: slack.errors.SlackApiError: The request to the Slack API failed.
Mar 12 14:38:30 ip-172-31-39-222 gunicorn[29651]: The server responded with: {'ok': False, 'error': 'invalid_arguments', 'response_metadata': {'messages': ['[ERROR] must provide a string [json-pointer:/channel]']}}
```

**Comment by itsthejoker** [comment]
Because we were unable to see private channels, the above error occurs anytime someone posts a question from a private channel

**Comment by itsthejoker** [comment]
Not fixed in https://github.com/KenzieAcademy/quackers/commit/dee06b69faa1a0ea82f588256309477d0c95e6f5

**Comment by itsthejoker** [comment]
I blame slack for this because I changed nothing materially and it's working. :man_shrugging:
